name: Build Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build com Maven
        run: mvn clean package

      - name: Publicar artefacto
        uses: actions/upload-artifact@v4
        with:
          name: build-jar
          path: target/*.jar
